import { randomBytes } from "node:crypto";
import type { ClawforceConfig } from "./types.js";

export function generateEnv(config: ClawforceConfig): string {
  const gatewayToken = randomBytes(32).toString("hex");

  const hooksToken = randomBytes(32).toString("hex");

  const lines = [
    "# Generated by Clawforce",
    `# Deployment: ${config.name}`,
    "# DO NOT COMMIT THIS FILE TO VERSION CONTROL",
    "",
    `GATEWAY_TOKEN=${gatewayToken}`,
    `HOOKS_TOKEN=${hooksToken}`,
    `ANTHROPIC_API_KEY=${config.models.api_key ?? ""}`,
  ];

  if (config.dashboard?.auth?.enabled) {
    const authSecret = randomBytes(32).toString("hex");
    lines.push("");
    lines.push("# Dashboard authentication");
    lines.push(`AUTH_SECRET=${authSecret}`);
    lines.push(`DASHBOARD_ADMIN_USERNAME=${config.dashboard.auth.username}`);
    lines.push(`DASHBOARD_ADMIN_PASSWORD=${config.dashboard.auth.password}`);
  }

  return lines.join("\n") + "\n";
}
