import { randomBytes } from "node:crypto";
import type { ClawforceConfig } from "./types.js";

export function generateEnv(config: ClawforceConfig): string {
  const gatewayToken = randomBytes(32).toString("hex");

  const hooksToken = randomBytes(32).toString("hex");
  const credentialMode = config.models.credential_mode ?? "env";

  const lines = [
    "# Generated by Clawforce",
    `# Deployment: ${config.name}`,
    "# DO NOT COMMIT THIS FILE TO VERSION CONTROL",
    "",
    `GATEWAY_TOKEN=${gatewayToken}`,
    `HOOKS_TOKEN=${hooksToken}`,
  ];

  if (credentialMode === "env") {
    const providerKeys = Object.entries(config.models.provider_keys ?? {}).sort((a, b) =>
      a[0].localeCompare(b[0])
    );
    for (const [provider, apiKey] of providerKeys) {
      lines.push(`${toProviderApiKeyEnvName(provider)}=${apiKey}`);
    }
    if (config.models.auth_profile) {
      lines.push(
        "# NOTE: models.auth_profile is configured but ignored because credential_mode=env",
      );
    }
  } else {
    lines.push("# Credential mode uses OpenClaw auth profile, not provider env vars");
    lines.push(`OPENCLAW_AUTH_PROFILE=${config.models.auth_profile ?? ""}`);
    if (config.models.provider_keys && Object.keys(config.models.provider_keys).length > 0) {
      lines.push(
        "# NOTE: models.provider_keys is configured but ignored because credential_mode=auth_profile",
      );
    }
  }

  if (config.dashboard?.auth?.enabled) {
    const authSecret = randomBytes(32).toString("hex");
    lines.push("");
    lines.push("# Dashboard authentication");
    lines.push(`AUTH_SECRET=${authSecret}`);
  }

  if (config.alerts?.notifications?.email?.password) {
    lines.push(`CLAWFORCE_ALERTS_EMAIL_PASSWORD=${config.alerts.notifications.email.password}`);
  }

  if (config.runtime?.location === "host") {
    lines.push("");
    lines.push("# Host runtime endpoint");
    if (config.runtime.engine === "ollama") {
      lines.push(`OLLAMA_HOST=${resolveHostRuntimeUrl(config)}`);
    } else if (config.runtime.engine === "vllm") {
      lines.push(`VLLM_HOST=${resolveHostRuntimeUrl(config)}`);
    } else {
      lines.push(`SGLANG_HOST=${resolveHostRuntimeUrl(config)}`);
    }
  }

  return lines.join("\n") + "\n";
}

function resolveHostRuntimeUrl(config: ClawforceConfig): string {
  const runtime = config.runtime;
  if (!runtime) return "";
  if (runtime.host_url) return runtime.host_url;
  if (runtime.engine === "ollama") return "http://host.docker.internal:11434";
  if (runtime.engine === "vllm") return `http://host.docker.internal:${runtime.port ?? 8000}`;
  return `http://host.docker.internal:${runtime.port ?? 30000}`;
}

function toProviderApiKeyEnvName(provider: string): string {
  return `${provider.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_API_KEY`;
}
