import { randomBytes } from "node:crypto";
import type { ClawforceConfig } from "./types.js";
import { getLocalModelEngine } from "./types.js";
import { getRuntimeEngineAdapter } from "./engines/registry.js";

export function generateEnv(config: ClawforceConfig): string {
  const gatewayToken = randomBytes(32).toString("hex");

  const hooksToken = randomBytes(32).toString("hex");

  const credentialMode = config.auth_profile ? "auth_profile" : "env";

  const lines = [
    "# Generated by Clawforce",
    `# Deployment: ${config.name}`,
    "# DO NOT COMMIT THIS FILE TO VERSION CONTROL",
    "",
    `GATEWAY_TOKEN=${gatewayToken}`,
    `HOOKS_TOKEN=${hooksToken}`,
  ];

  if (credentialMode === "env") {
    const seenProviders = new Set<string>();
    const cloudModels = config.models?.filter((m) => m.type === "cloud" && m.api_key) ?? [];
    for (const m of cloudModels) {
      const provider = m.id.split("/")[0];
      if (!seenProviders.has(provider)) {
        seenProviders.add(provider);
        lines.push(`${toProviderApiKeyEnvName(provider)}=${m.api_key!}`);
      }
    }
  } else {
    lines.push("# Credential mode uses OpenClaw auth profile, not provider env vars");
    lines.push(`OPENCLAW_AUTH_PROFILE=${config.auth_profile ?? ""}`);
  }

  if (config.dashboard?.auth?.enabled) {
    const authSecret = randomBytes(32).toString("hex");
    lines.push("");
    lines.push("# Dashboard authentication");
    lines.push(`AUTH_SECRET=${authSecret}`);
  }

  if (config.alerts?.notifications?.email?.password) {
    lines.push(`CLAWFORCE_ALERTS_EMAIL_PASSWORD=${config.alerts.notifications.email.password}`);
  }

  const localEngine = getLocalModelEngine(config);
  if (localEngine?.location === "host") {
    const adapter = getRuntimeEngineAdapter(localEngine.runtime);
    lines.push("");
    lines.push("# Host runtime endpoint");
    lines.push(`${adapter.hostEnvVarName}=${adapter.resolveHostRuntimeUrl(localEngine)}`);
  }

  return lines.join("\n") + "\n";
}

function toProviderApiKeyEnvName(provider: string): string {
  return `${provider.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_API_KEY`;
}
